const CACHE='bpd-somagede-v17-catalog-fast-20260810';
const TRAFFIC_API='https://bpd-somagede-cms.bpddesasomagede.workers.dev';
const META_CACHE='bpd-traffic-device-v1';
const PRECACHE=['index.html','profil.html','kepala-desa.html','pembangunan.html','dokumen.html','aspirasi.html','kontak.html','bpd-portal-berita.js','bpd-portal-berita.css','assets/logo-bpd.webp','assets/logo-kab.webp','assets/book-fallback/education.webp','assets/book-fallback/history.webp','assets/book-fallback/government.webp','assets/book-fallback/technology.webp','assets/book-fallback/religion.webp','assets/book-fallback/literature.webp'];
async function metaGet(key){const c=await caches.open(META_CACHE);const r=await c.match(new Request(`${self.location.origin}/__bpd_meta__/${key}`));return r?await r.text():''}
async function metaSet(key,value){const c=await caches.open(META_CACHE);await c.put(new Request(`${self.location.origin}/__bpd_meta__/${key}`),new Response(String(value),{headers:{'content-type':'text/plain'}}))}
async function visitorId(){let id=await metaGet('visitor-id');if(!id){id=(crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`);await metaSet('visitor-id',id)}return id}
async function isAdminDevice(){return(await metaGet('admin-device'))==='1'}
async function trackNavigation(pathname){try{if(pathname.endsWith('/editor.html')||pathname.includes('/editor.html'))return;if(await isAdminDevice())return;const id=await visitorId();await fetch(`${TRAFFIC_API}/api/traffic/visit`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({client_id:id,path:pathname,admin:false}),cache:'no-store'})}catch{}}
self.addEventListener('message',e=>{const d=e.data||{};if(d.type==='BPD_ADMIN_DEVICE')e.waitUntil(metaSet('admin-device',d.value===false?'0':'1'))});
self.addEventListener('install',e=>e.waitUntil((async()=>{const c=await caches.open(CACHE);await Promise.allSettled(PRECACHE.map(u=>c.add(new Request(u,{cache:'reload'}))));await self.skipWaiting()})()));
self.addEventListener('activate',e=>e.waitUntil((async()=>{for(const k of await caches.keys())if(k!==CACHE&&k!==META_CACHE)await caches.delete(k);await self.clients.claim()})()));
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const u=new URL(r.url);if(u.origin!==self.location.origin){e.respondWith(fetch(r));return}const isPortalAsset=u.pathname.endsWith('/bpd-portal-berita.js')||u.pathname.endsWith('/bpd-portal-berita.css');const isDocument=r.mode==='navigate'||r.destination==='document';if(isDocument)e.waitUntil(trackNavigation(u.pathname));if(isDocument||isPortalAsset){e.respondWith((async()=>{try{const res=await fetch(r,{cache:'no-store'});if(res&&res.ok){const c=await caches.open(CACHE);await c.put(r,res.clone())}return res}catch{return(await caches.match(r))||(isDocument?await caches.match('index.html'):null)||Response.error()}})());return}e.respondWith((async()=>{const cached=await caches.match(r);const network=fetch(r).then(async res=>{if(res&&res.ok){const c=await caches.open(CACHE);await c.put(r,res.clone())}return res}).catch(()=>null);return cached||(await network)||Response.error()})())});